org: gejsi
app: funx
service: funx

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: eu-central-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - lambda:InvokeFunction
        - lambda:InvokeAsync
      Resource: '*'

functions:
  hello:
    handler: hello.greet

plugins:
  - serverless-offline
  - serverless-esbuild
